apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ include "helm.fullname" . }}-deployment'
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  strategy:
    type: {{ .Values.frontend.strategy.type }}
    {{- if eq .Values.frontend.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.frontend.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.frontend.strategy.rollingUpdate.maxUnavailable }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: config-volume
          configMap:
            name: '{{ include "helm.fullname" . }}-configmap'
            items:
              - key: default.conf
                path: default.conf