frontend:
  name: frontend
  replicaCount: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  image:
    repository: ghcr.io/nguyentukien/unipoint-frontend
    tag: latest
    pullPolicy: Always
  service:
    type: NodePort
    port: 80
    nodePort: 30030

backend:
  name: unipoint-backend
  service:
    port: 8080
