backend:
  name: unipoint-backend
  replicaCount: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  image:
    repository: ngtukien218/ttcs-backend
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
  environment:
    SPRING_PROFILES_ACTIVE: "default"
    # Datasource
    SPRING_DATASOURCE_URL: "jdbc:postgresql://unipoint-database:5432/unipointdb?prepareThreshold=0"
    SPRING_DATASOURCE_USERNAME: "group06"
    # Redis
    SPRING_DATA_REDIS_HOST: "unipoint-redis"
    SPRING_DATA_REDIS_PORT: "6379"
    # RabbitMQ
    SPRING_RABBITMQ_HOST: "unipoint-rabbitmq"
    SPRING_RABBITMQ_PORT: "5672"
    SPRING_RABBITMQ_USERNAME: "guest"
    SPRING_RABBITMQ_VIRTUAL_HOST: "/"
    SPRING_RABBITMQ_SSL_ENABLED: "false"
    # Mail
    SPRING_MAIL_HOST: "smtp.gmail.com"
    SPRING_MAIL_PORT: "587"
    SPRING_MAIL_USERNAME: ""
    # App
    CORS_ALLOWED_ORIGINS: "*"
    SPRING_APP_SEEDER_ENABLED: "false"
    # OAuth2
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MICROSOFT_REDIRECT_URI: "http://localhost:8080/api/login/oauth2/code/microsoft"
    SPRING_APP_OAUTH2_REDIRECT_URL: "http://localhost:3000/oauth-success"
    # Device
    DEVICE_SECURITY_COOKIE_NAME: "device_token"
    DEVICE_SECURITY_COOKIE_SECURE: "false"
    DEVICE_BINDING_TTL_MS: "604800000"
    # JWT
    JWT_EXPIRATION_MS: "86400000"
    JWT_REFRESH_EXPIRATION_MS: "604800000"
  secrets:
    SPRING_DATASOURCE_PASSWORD: "ttcs_2026"
    SPRING_DATA_REDIS_PASSWORD: "TTCS_2026"
    SPRING_RABBITMQ_PASSWORD: "guest"
    SPRING_MAIL_PASSWORD: ""
    JWT_SECRET: "GenerateYourOwnSecureSecretKeyHereMinimum32Chars"
    DEVICE_SECURITY_HMAC_SECRET: "ChangeThisHMACSecretKeyForProduction"
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MICROSOFT_CLIENT_ID: ""
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MICROSOFT_CLIENT_SECRET: ""