spring:
  main:
    banner-mode: "off"
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://${DB_HOST:db.yqxkojuxhtsgwxhtlkzc.supabase.co}:${DB_PORT:5432}/${POSTGRES_DB:unipointdb}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:TTCS_CT01_N06}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: warn

management:
  endpoints:
    web:
      exposure:
        include: "*"