apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "helm.fullname" . }}-configmap'
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: "{{ .Values.backend.environment.SPRING_PROFILES_ACTIVE }}"
  # Postgres
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Values.backend.environment.POSTGRES_HOST }}:{{ .Values.backend.environment.POSTGRES_PORT }}/{{ .Values.backend.environment.POSTGRES_DB }}"
  SPRING_DATASOURCE_USERNAME: "{{ .Values.backend.environment.POSTGRES_USER }}"
  # Redis
  SPRING_DATA_REDIS_HOST: "{{ .Values.backend.environment.REDIS_HOST }}"
  SPRING_DATA_REDIS_PORT: "{{ .Values.backend.environment.REDIS_PORT }}"
  # RabbitMQ
  SPRING_RABBITMQ_HOST: "{{ .Values.backend.environment.RABBITMQ_HOST }}"
  SPRING_RABBITMQ_PORT: "{{ .Values.backend.environment.RABBITMQ_PORT }}"
  SPRING_RABBITMQ_USERNAME: "{{ .Values.backend.environment.RABBITMQ_USERNAME }}"
  SPRING_RABBITMQ_VIRTUAL_HOST: "{{ .Values.backend.environment.RABBITMQ_VIRTUAL_HOST }}"
  SPRING_RABBITMQ_SSL_ENABLED: "{{ .Values.backend.environment.RABBITMQ_SSL_ENABLED }}"
  # CORS
  CORS_ALLOWED_ORIGINS: "{{ .Values.backend.environment.CORS_ALLOWED_ORIGINS }}"
  APP_SEEDER_ENABLED: "{{ .Values.backend.environment.APP_SEEDER_ENABLED }}"
  # OAuth2 & Device
  APP_OAUTH2_REDIRECT_URL: "{{ .Values.backend.environment.OAUTH2_REDIRECT_URL }}"
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MICROSOFT_REDIRECT_URI: "{{ .Values.backend.environment.OAUTH2_REDIRECT_URI }}"
  DEVICE_SECURITY_COOKIE_NAME: "{{ .Values.backend.environment.DEVICE_COOKIE_NAME }}"
  DEVICE_SECURITY_COOKIE_SECURE: "{{ .Values.backend.environment.DEVICE_COOKIE_SECURE }}"
  DEVICE_BINDING_TTL_MS: "{{ .Values.backend.environment.DEVICE_BINDING_TTL_MS }}"
  JWT_EXPIRATION_MS: "{{ .Values.backend.environment.JWT_EXPIRATION_MS }}"
  JWT_REFRESH_EXPIRATION_MS: "{{ .Values.backend.environment.JWT_REFRESH_EXPIRATION_MS }}"
  # Mail
  SPRING_MAIL_HOST: {{ .Values.backend.environment.MAIL_HOST | default "smtp.gmail.com" | quote }}
  SPRING_MAIL_PORT: {{ .Values.backend.environment.MAIL_PORT | default "587" | quote }}
  SPRING_MAIL_USERNAME: "{{ .Values.backend.environment.MAIL_USERNAME }}"