apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "helm.fullname" . }}-configmap'
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: "{{ .Values.backend.environment.SPRING_PROFILES_ACTIVE }}"
  # Postgres
  POSTGRES_HOST: "{{ .Values.backend.environment.POSTGRES_HOST }}"
  POSTGRES_PORT: "{{ .Values.backend.environment.POSTGRES_PORT }}"
  POSTGRES_DB: "{{ .Values.backend.environment.POSTGRES_DB }}"
  POSTGRES_USER: "{{ .Values.backend.environment.POSTGRES_USER }}"
  # Redis
  REDIS_HOST: "{{ .Values.backend.environment.REDIS_HOST }}"
  REDIS_PORT: "{{ .Values.backend.environment.REDIS_PORT }}"
  # RabbitMQ
  RABBITMQ_HOST: "{{ .Values.backend.environment.RABBITMQ_HOST }}"
  RABBITMQ_PORT: "{{ .Values.backend.environment.RABBITMQ_PORT }}"
  RABBITMQ_USERNAME: "{{ .Values.backend.environment.RABBITMQ_USERNAME }}"
  RABBITMQ_VIRTUAL_HOST: "{{ .Values.backend.environment.RABBITMQ_VIRTUAL_HOST }}"
  RABBITMQ_SSL_ENABLED: "{{ .Values.backend.environment.RABBITMQ_SSL_ENABLED }}"
  # CORS
  CORS_ALLOWED_ORIGINS: "{{ .Values.backend.environment.CORS_ALLOWED_ORIGINS }}"
  APP_SEEDER_ENABLED: "{{ .Values.backend.environment.APP_SEEDER_ENABLED }}"
  # OAuth2 & Device
  OAUTH2_REDIRECT_URL: "{{ .Values.backend.environment.OAUTH2_REDIRECT_URL }}"
  OAUTH2_REDIRECT_URI: "{{ .Values.backend.environment.OAUTH2_REDIRECT_URI }}"
  DEVICE_COOKIE_NAME: "{{ .Values.backend.environment.DEVICE_COOKIE_NAME }}"
  DEVICE_COOKIE_SECURE: "{{ .Values.backend.environment.DEVICE_COOKIE_SECURE }}"
  DEVICE_BINDING_TTL_MS: "{{ .Values.backend.environment.DEVICE_BINDING_TTL_MS }}"
  JWT_EXPIRATION_MS: "{{ .Values.backend.environment.JWT_EXPIRATION_MS }}"
  JWT_REFRESH_EXPIRATION_MS: "{{ .Values.backend.environment.JWT_REFRESH_EXPIRATION_MS }}"
  MAIL_USERNAME: "{{ .Values.backend.environment.MAIL_USERNAME }}"