apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "helm.fullname" . }}-secret'
  labels:
    {{- include "helm.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.backend.secrets.POSTGRES_PASSWORD | quote }}
  REDIS_PASSWORD: {{ .Values.backend.secrets.REDIS_PASSWORD | quote }}
  RABBITMQ_PASSWORD: {{ .Values.backend.secrets.RABBITMQ_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.backend.secrets.JWT_SECRET | quote }}
  DEVICE_HMAC_SECRET: {{ .Values.backend.secrets.DEVICE_HMAC_SECRET | quote }}
  MICROSOFT_CLIENT_ID: {{ .Values.backend.secrets.MICROSOFT_CLIENT_ID | quote }}
  MICROSOFT_CLIENT_SECRET: {{ .Values.backend.secrets.MICROSOFT_CLIENT_SECRET | quote }}
  MAIL_APP_PASSWORD: {{ .Values.backend.secrets.MAIL_APP_PASSWORD | quote }}