apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "helm.fullname" . }}-secret'
  labels:
    {{- include "helm.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.backend.secrets.SPRING_DATASOURCE_PASSWORD | quote }}
  SPRING_DATA_REDIS_PASSWORD: {{ .Values.backend.secrets.SPRING_DATA_REDIS_PASSWORD | quote }}
  SPRING_RABBITMQ_PASSWORD: {{ .Values.backend.secrets.SPRING_RABBITMQ_PASSWORD | quote }}
  SPRING_MAIL_PASSWORD: {{ .Values.backend.secrets.SPRING_MAIL_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.backend.secrets.JWT_SECRET | quote }}
  DEVICE_SECURITY_HMAC_SECRET: {{ .Values.backend.secrets.DEVICE_SECURITY_HMAC_SECRET | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MICROSOFT_CLIENT_ID: {{ .Values.backend.secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MICROSOFT_CLIENT_ID | quote }}
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MICROSOFT_CLIENT_SECRET: {{ .Values.backend.secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_MICROSOFT_CLIENT_SECRET | quote }}