apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ include "helm.fullname" . }}-deployment'
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  strategy:
    type: {{ .Values.backend.strategy.type }}
    {{ if eq .Values.backend.strategy.type "RollingUpdate" }}
    rollingUpdate:
      maxSurge: {{ .Values.backend.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.backend.strategy.rollingUpdate.maxUnavailable }}
    {{ end }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: "{{ .Values.backend.image.pullPolicy }}"
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          envFrom:
            - configMapRef:
                name: '{{ include "helm.fullname" . }}-configmap'
            - secretRef:
                name: '{{ include "helm.fullname" . }}-secret'
          volumeMounts:
            - name: log-volume
              mountPath: /app/logs
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.service.port }}
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: log-volume
          emptyDir: {}